import { defineComponent, h } from 'vue'
import UiIcon from '@/components/ui/icon/UiIcon.vue'

function createCompatIcon(name: string) {
  return defineComponent({
    name,
    setup() {
      return () => h(UiIcon, { name })
    },
  })
}

export const ArrowDown = createCompatIcon('ArrowDown')
export const ArrowLeft = createCompatIcon('ArrowLeft')
export const ArrowRight = createCompatIcon('ArrowRight')
export const ArrowUp = createCompatIcon('ArrowUp')
export const Back = createCompatIcon('Back')
export const Bottom = createCompatIcon('Bottom')
export const Calendar = createCompatIcon('Calendar')
export const Camera = createCompatIcon('Camera')
export const ChatDotRound = createCompatIcon('ChatDotRound')
export const Close = createCompatIcon('Close')
export const Compass = createCompatIcon('Compass')
export const Delete = createCompatIcon('Delete')
export const Edit = createCompatIcon('Edit')
export const EditPen = createCompatIcon('EditPen')
export const Folder = createCompatIcon('Folder')
export const Grid = createCompatIcon('Grid')
export const Headset = createCompatIcon('Headset')
export const HomeFilled = createCompatIcon('home')
export const InfoFilled = createCompatIcon('InfoFilled')
export const Link = createCompatIcon('Link')
export const List = createCompatIcon('List')
export const Loading = createCompatIcon('Loading')
export const Location = createCompatIcon('Location')
export const MapLocation = createCompatIcon('MapLocation')
export const Menu = createCompatIcon('Menu')
export const Message = createCompatIcon('Message')
export const Minus = createCompatIcon('Minus')
export const Moon = createCompatIcon('moon')
export const Place = createCompatIcon('location')
export const Plus = createCompatIcon('Plus')
export const Postcard = createCompatIcon('Postcard')
export const Rank = createCompatIcon('Rank')
export const Refresh = createCompatIcon('Refresh')
export const Right = createCompatIcon('Right')
export const Search = createCompatIcon('Search')
export const Setting = createCompatIcon('Setting')
export const Sort = createCompatIcon('Sort')
export const Star = createCompatIcon('Star')
export const StarFilled = createCompatIcon('StarFilled')
export const Sunny = createCompatIcon('sun')
export const SwitchButton = createCompatIcon('SwitchButton')
export const Top = createCompatIcon('Top')
export const User = createCompatIcon('User')
export const UserFilled = createCompatIcon('UserFilled')
export const VideoPause = createCompatIcon('VideoPause')
export const VideoPlay = createCompatIcon('VideoPlay')
export const View = createCompatIcon('View')
