/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppActionBar: typeof import('./components/app/AppActionBar/AppActionBar.vue')['default']
    AppEmptyState: typeof import('./components/app/AppEmptyState/AppEmptyState.vue')['default']
    AppFilterBar: typeof import('./components/app/AppFilterBar/AppFilterBar.vue')['default']
    AppSection: typeof import('./components/app/AppSection/AppSection.vue')['default']
    AppStatusPill: typeof import('./components/app/AppStatusPill/AppStatusPill.vue')['default']
    ArticleCard: typeof import('./components/ArticleCard/ArticleCard.vue')['default']
    CategoryIcon: typeof import('./components/CategoryIcon/CategoryIcon.vue')['default']
    CommentItem: typeof import('./components/Comment/CommentItem.vue')['default']
    CommentSection: typeof import('./components/Comment/CommentSection.vue')['default']
    EmojiPickerPanel: typeof import('./components/Emoji/EmojiPickerPanel.vue')['default']
    FeatureAccessCover: typeof import('./components/FeatureAccessCover.vue')['default']
    Footer: typeof import('./components/Footer/Footer.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    HeroImageFocusEditor: typeof import('./components/HeroImageFocusEditor/HeroImageFocusEditor.vue')['default']
    HeroSubtitlePulse: typeof import('./components/PageHero/HeroSubtitlePulse.vue')['default']
    HeroWave: typeof import('./components/HeroWave/HeroWave.vue')['default']
    HomeDiscoverySearch: typeof import('./components/HomeDiscoverySearch/HomeDiscoverySearch.vue')['default']
    Live2D: typeof import('./components/Live2D/Live2D.vue')['default']
    Live2DChatPanel: typeof import('./components/Live2D/Live2DChatPanel.vue')['default']
    Live2DMusicPanel: typeof import('./components/Live2D/Live2DMusicPanel.vue')['default']
    MdEditorEmojiToolbar: typeof import('./components/Editor/MdEditorEmojiToolbar.vue')['default']
    MdEditorUnorderedListToolbar: typeof import('./components/Editor/MdEditorUnorderedListToolbar.vue')['default']
    MdResizablePreview: typeof import('./components/MdResizablePreview/MdResizablePreview.vue')['default']
    PageHero: typeof import('./components/PageHero/PageHero.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SakuraOverlay: typeof import('./components/SakuraOverlay/SakuraOverlay.vue')['default']
    TravelMemoryMap: typeof import('./components/TravelMemoryMap/TravelMemoryMap.vue')['default']
    TravelPhotoSphere: typeof import('./components/TravelMemoryMap/TravelPhotoSphere.vue')['default']
    UiAvatar: typeof import('./components/ui/avatar/UiAvatar.vue')['default']
    UiBadge: typeof import('./components/ui/badge/UiBadge.vue')['default']
    UiButton: typeof import('./components/ui/button/UiButton.vue')['default']
    UiCheckbox: typeof import('./components/ui/checkbox/UiCheckbox.vue')['default']
    UiDateField: typeof import('./components/ui/date-field/UiDateField.vue')['default']
    UiDialog: typeof import('./components/ui/dialog/UiDialog.vue')['default']
    UiDivider: typeof import('./components/ui/divider/UiDivider.vue')['default']
    UiDrawer: typeof import('./components/ui/drawer/UiDrawer.vue')['default']
    UiDropdown: typeof import('./components/ui/dropdown/UiDropdown.vue')['default']
    UiDropdownItem: typeof import('./components/ui/dropdown-item/UiDropdownItem.vue')['default']
    UiDropdownMenu: typeof import('./components/ui/dropdown-menu/UiDropdownMenu.vue')['default']
    UiEmpty: typeof import('./components/ui/empty/UiEmpty.vue')['default']
    UiForm: typeof import('./components/ui/form/UiForm.vue')['default']
    UiFormField: typeof import('./components/ui/form-field/UiFormField.vue')['default']
    UiIcon: typeof import('./components/ui/icon/UiIcon.vue')['default']
    UiInput: typeof import('./components/ui/input/UiInput.vue')['default']
    UiLoadingState: typeof import('./components/ui/loading-state/UiLoadingState.vue')['default']
    UiNumberField: typeof import('./components/ui/number-field/UiNumberField.vue')['default']
    UiPagination: typeof import('./components/ui/pagination/UiPagination.vue')['default']
    UiPanel: typeof import('./components/ui/panel/UiPanel.vue')['default']
    UiRadioGroup: typeof import('./components/ui/radio-group/UiRadioGroup.vue')['default']
    UiSearchBar: typeof import('./components/ui/search-bar/UiSearchBar.vue')['default']
    UiSegmented: typeof import('./components/ui/segmented/UiSegmented.vue')['default']
    UiSelect: typeof import('./components/ui/select/UiSelect.vue')['default']
    UiSkeleton: typeof import('./components/ui/skeleton/UiSkeleton.vue')['default']
    UiSlider: typeof import('./components/ui/slider/UiSlider.vue')['default']
    UiSwitch: typeof import('./components/ui/switch/UiSwitch.vue')['default']
    UiTable: typeof import('./components/ui/table/UiTable.vue')['default']
    UiTableColumn: typeof import('./components/ui/table-column/UiTableColumn.vue')['default']
    UiTabs: typeof import('./components/ui/tabs/UiTabs.vue')['default']
    UiTextarea: typeof import('./components/ui/textarea/UiTextarea.vue')['default']
    UiTooltip: typeof import('./components/ui/tooltip/UiTooltip.vue')['default']
    UiUpload: typeof import('./components/ui/upload/UiUpload.vue')['default']
    UserProfileCard: typeof import('./components/UserProfile/UserProfileCard.vue')['default']
    UserProfilePopover: typeof import('./components/UserProfile/UserProfilePopover.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
